name: upload-website

on:
  push:
    branches:
    - master

env:
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'eu-west-2'
  SOURCE_DIR: './site'
  DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}

jobs:
  deploy:
    name: Deploy web to S3 (dev)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install node dependencies
      run: npm install
    - name: Run gulp task runner
      run: gulp build
      env:
        CF_SPACE: ${{ secrets.CF_SPACE }}
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
    - name: Deploy files to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
    - name: Invalidate CloudFront edge files
      uses: awact/cloudfront-action@master
      env:
        SOURCE_DIR: '/*'